-- drop tables data script version 1.5, lastChanged: 17.02.2008


--DROP TABLE IF EXISTS dayinfo;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dayinfo')
DROP TABLE dayinfo


--DROP TABLE IF EXISTS phone_staffmember;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'phone_staffmember')
DROP TABLE phone_staffmember


--DROP TABLE IF EXISTS staffmember_competence;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'staffmember_competence')
DROP TABLE staffmember_competence

--DROP TABLE IF EXISTS transport_selected;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'transport_selected')
DROP TABLE transport_selected

--DROP TABLE IF EXISTS selected;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'selected')
DROP TABLE selected

--DROP TABLE IF EXISTS tmptransports;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tmptransports')
DROP TABLE tmptransports

--DROP TABLE IF EXISTS assigned_vehicle;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'assigned_vehicle')
DROP TABLE assigned_vehicle

--DROP TABLE IF EXISTS transportstate;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'transportstate')
DROP TABLE transportstate

--DROP TABLE IF EXISTS vehicles;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'vehicles')
DROP TABLE vehicles

--DROP TABLE IF EXISTS roster;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'roster')
DROP TABLE roster

--DROP TABLE IF EXISTS transports;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'transports')
DROP TABLE transports

--DROP TABLE IF EXISTS caller;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'caller')
DROP TABLE caller

--DROP TABLE IF EXISTS staffmembers;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'staffmembers')
DROP TABLE staffmembers

--DROP TABLE IF EXISTS job;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'job')
DROP TABLE job

--DROP TABLE IF EXISTS servicetype;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'servicetype')
DROP TABLE servicetype

--DROP TABLE IF EXISTS competences;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'competences')
DROP TABLE competences

--DROP TABLE IF EXISTS dialysis_transport;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dialysis_transport')
DROP TABLE dialysis_transport

--DROP TABLE IF EXISTS dialysis;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'dialysis')
DROP TABLE dialysis

--DROP TABLE IF EXISTS location;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'location')
DROP TABLE location

--DROP TABLE IF EXISTS phonenumbers;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'phonenumbers')
DROP TABLE phonenumbers

--DROP TABLE IF EXISTS disease;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'disease')
DROP TABLE disease

--DROP TABLE IF EXISTS userlogin;
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'userlogin')
DROP TABLE userlogin